<a href="https://colab.research.google.com/github/hruthiksiva/basic-ml-practice/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing

In [2]:
import numpy as np

# Numpy Arrays

## Creating numpy arrays

In [3]:
arr1 = np.array([1,2,3,4])

arr2 = np.array([
    [1,2,3,4],
    [2,3,4,5]
]

)
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [4]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
range_arr = np.arange(0,10,2) # start stop step
range_arr

array([0, 2, 4, 6, 8])

In [9]:
linspace = np.linspace(0,5,5)
linspace

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

## Array Properties

In [12]:
arr = np.array(
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
)
print(arr.shape)
print(arr.size)
print(arr.dtype)

(2, 4)
8
int64


## Reshaping and Flattern

In [19]:
reshaped = arr.reshape(8,1)
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [16]:
flattened = arr.flatten()
print(flattened)

[1 2 3 4 5 6 7 8]


# Indexing and Slicing

In [20]:
# accessing specific elements
print(arr[1][2])

7


In [22]:
# slicing
print(arr[:,1])
print(arr[1,:])

[2 6]
[5 6 7 8]


# Array Operations

## Arithmetic

In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## Universal Functions

In [25]:
print(np.sqrt(b))
print(np.exp(b))

[2.         2.23606798 2.44948974]
[ 54.59815003 148.4131591  403.42879349]


## Broadcasting

In [26]:
c = 3
print(a*c)

[3 6 9]


## Stastical Function

In [28]:
print(np.mean(a))
print(np.std(a))
print(np.sum(a))
print(np.min(a))
print(np.max(a))


2.0
0.816496580927726
6
1
3


# Random

In [31]:
rand_float = np.random.rand(5)
print(rand_float)

[0.87149753 0.46059312 0.90267925 0.5403108  0.048978  ]


In [33]:
rand_int = np.random.randint(0,10,(3,3))
print(rand_int)

[[1 1 7]
 [3 2 4]
 [5 4 4]]


# Linear Algebra

In [34]:
# Matrix Multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.dot(a, b)
print(result)

[[19 22]
 [43 50]]


In [36]:
# Matrix Multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.cross(a, b)
print(result)

[-4 -4]


In [35]:
print(a.T)

[[1 3]
 [2 4]]


# Example Scenario

In [37]:
sensor_data = np.array([23.5, 24.8, 22.9, 23.1, 24.2])
average = np.mean(sensor_data)
print(f"Average sensor reading: {average}")

Average sensor reading: 23.699999999999996


In [38]:
image = np.array([[100, 150], [200, 250]])  # Grayscale values
brightened = image + 50  # Increase brightness
print(brightened)


[[150 200]
 [250 300]]


In [39]:
prices = np.array([100, 102, 105, 107])
returns = np.diff(prices) / prices[:-1] * 100
print(f"Daily returns (%): {returns}")


Daily returns (%): [2.         2.94117647 1.9047619 ]


In [40]:
data = np.array([[10, 200], [20, 300], [15, 250]])
mean = np.mean(data, axis=0)
std_dev = np.std(data, axis=0)

standardized = (data - mean) / std_dev
print(standardized)


[[-1.22474487 -1.22474487]
 [ 1.22474487  1.22474487]
 [ 0.          0.        ]]


In [41]:
A = np.array([[3, 1], [1, 2]])
B = np.array([9, 8])

x = np.linalg.solve(A, B)
print(x)


[2. 3.]
